### ISSUE TITLE
How to generate c code for embedded control?

### ISSUE THREAD

**Issue by merdan-9** [TUM-AAS/ml-casadi#1]
Hello,

I would like to use a PyTorch model as the dynamics model for Model Predictive Control in the Acados framework and subsequently deploy it to an embedded controller using C code.

What is the best practice for generating C code, and are there any restrictions on the network structure and parameter size?

Thank you for your time!

**Comment by Tim-Salzmann** [comment]
Hi Merdan,

Please see our new framework for exactly this use case: https://github.com/Tim-Salzmann/l4casadi

Feel free to ask questions there if you ned assistance.

Best,
Tim
